name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
      - test

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用该时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: Build-and-deploy # 步骤3
        run: |
          commit_info=`git describe --all --always --long`
          user_name=`git log -1 --pretty=format:'%an'`
          user_email=`git log -1 --pretty=format:'%ae'`
          git config user.name ${user_name}
          git config user.email ${user_email}

          # 处理当前仓库
          yarn
          yarn build
          if test -z "$(git status -uno --porcelain | cut -c4-)"; then
            echo "无文件变更"
          else
            git commit -am "chore: auto update files, $commit_info"
            git remote add origin https://${user_name}:${{secrets.GITHUB_TOKEN}}@github.com:francecil/blog.git
            git push origin HEAD:$deploy_branch # 推送到github $deploy_branch分支
          fi